# Generated by Django 4.1.3 on 2022-11-23 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Racket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('brand', models.CharField(choices=[('Vibora', 'vibora'), ('Bullpadel', 'bullpadel')], default='Vibora', max_length=30)),
                ('model', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('model', models.IntegerField()),
                ('brand', models.CharField(choices=[('Asics', 'asics'), ('Bullpadel', 'bullpadel'), ('Wilson', 'wilson')], default='Asics', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ShoeAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.FloatField()),
                ('available_stock', models.IntegerField()),
                ('price', models.FloatField()),
                ('shoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.shoes')),
            ],
        ),
        migrations.CreateModel(
            name='RacketAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('available_stock', models.IntegerField()),
                ('price', models.FloatField()),
                ('racket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.racket')),
            ],
        ),
        migrations.AddConstraint(
            model_name='shoeavailability',
            constraint=models.UniqueConstraint(fields=('shoe', 'size'), name='One shoe object can only have one size for the specific stock'),
        ),
        migrations.AddConstraint(
            model_name='racketavailability',
            constraint=models.UniqueConstraint(fields=('racket', 'weight'), name='A racket with a specific weight can only have a available stock and a price'),
        ),
    ]
