# Generated by Django 4.1.3 on 2022-11-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmeasures',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='item',
            name='brand',
            field=models.CharField(choices=[('bullpadel', 'Bullpadel'), ('wilson', 'Wilson'), ('vibora', 'Vibora'), ('asics', 'Asics')], max_length=15),
        ),
    ]
