# Generated by Django 4.1.3 on 2022-11-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_reviewitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewitem',
            name='rating_stars',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=5),
        ),
    ]
