# Generated by Django 4.1.3 on 2022-11-29 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_reviewitem_rating_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.item'),
        ),
    ]
